// ── 可运行工程包导出（P1 收尾）──
// Code 面板里的代码只是"片段"，用户拿到手还要自己搭脚手架。
// 这里把导出的组件代码包成一个 `npm install && npm run dev` 就能跑的
// Vite 工程 zip——"从设计到代码"价值闭环的最后一块。
//
// 纯函数部分（splitReactCss / buildProjectFiles / buildProjectZip）不依赖
// 浏览器 API，可直接被 vitest 单测；只有 downloadProjectZip 触碰 DOM。

import { strToU8, zipSync } from 'fflate'

import type { CodeFramework } from '@/stores/code-output'

/**
 * selectionToCode 的 react 格式把 CSS 以块注释塞在 tsx 末尾：
 *   import './styles.css'
 *   export function X() { ... }
 *   /* styles.css *​/
 *   /​* ...css... *​/
 * 直接跑会报错（styles.css 不存在），这里拆成两个真实文件。
 */
export function splitReactCss(code: string): { tsx: string; css: string } {
  const marker = /\/\*\s*styles\.css\s*\*\//
  const match = code.match(marker)
  if (!match || match.index === undefined) {
    return { tsx: code.trimEnd() + '\n', css: '' }
  }
  const tsx = code.slice(0, match.index).trimEnd() + '\n'
  const rest = code.slice(match.index + match[0].length).trim()
  // rest 形如 /* ...css... */
  const css = rest.replace(/^\/\*/, '').replace(/\*\/\s*$/, '').trim() + '\n'
  return { tsx, css }
}

/** 从导出的 React 代码里取出组件名（App.tsx 要 import 它） */
function reactComponentName(tsx: string): string {
  const m = tsx.match(/export function (\w+)/)
  return m?.[1] ?? 'Component'
}

function readme(framework: CodeFramework): string {
  return `# Generated by Lutris.ai

A runnable ${framework} project exported from your canvas design.

\`\`\`bash
npm install
npm run dev
\`\`\`

Then open the printed localhost URL. The exported component lives in
\`src/\` — every class in the CSS maps 1:1 to a layer on your canvas.
`
}

const TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "jsx": "react-jsx",
    "skipLibCheck": true,
    "noEmit": true
  },
  "include": ["src"]
}
`

function vueFiles(componentCode: string): Record<string, string> {
  return {
    'package.json':
      JSON.stringify(
        {
          name: 'lutris-export-app',
          private: true,
          version: '0.1.0',
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'vite build',
            preview: 'vite preview',
          },
          dependencies: { vue: '^3.5.13' },
          devDependencies: {
            '@vitejs/plugin-vue': '^5.2.1',
            typescript: '^5.7.3',
            vite: '^6.0.7',
          },
        },
        null,
        2
      ) + '\n',
    'vite.config.ts': `import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
})
`,
    'index.html': `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Lutris Export</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
`,
    'src/main.ts': `import { createApp } from 'vue'
import App from './App.vue'

createApp(App).mount('#app')
`,
    // 导出的 SFC 自带 <style scoped>，直接当根组件用
    'src/App.vue': componentCode.trimEnd() + '\n',
    'tsconfig.json': TSCONFIG,
    'README.md': readme('Vue'),
  }
}

function reactFiles(componentCode: string): Record<string, string> {
  const { tsx, css } = splitReactCss(componentCode)
  const name = reactComponentName(tsx)
  return {
    'package.json':
      JSON.stringify(
        {
          name: 'lutris-export-app',
          private: true,
          version: '0.1.0',
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'vite build',
            preview: 'vite preview',
          },
          dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' },
          devDependencies: {
            '@types/react': '^18.3.18',
            '@types/react-dom': '^18.3.5',
            '@vitejs/plugin-react': '^4.3.4',
            typescript: '^5.7.3',
            vite: '^6.0.7',
          },
        },
        null,
        2
      ) + '\n',
    'vite.config.ts': `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
`,
    'index.html': `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Lutris Export</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
    'src/main.tsx': `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
)
`,
    'src/App.tsx': `import { ${name} } from './Component'

export default function App() {
  return <${name} />
}
`,
    'src/Component.tsx': tsx,
    // tsx 里 import './styles.css'，Component.tsx 与 styles.css 同目录即可
    'src/styles.css': css || '/* no styles were generated for this component */\n',
    'tsconfig.json': TSCONFIG,
    'README.md': readme('React'),
  }
}

/**
 * 把单个框架的导出代码组装成可运行 Vite 工程的文件表。
 * HTML 导出本身即是完整页面，无需脚手架，不在此列。
 */
export function buildProjectFiles(
  framework: CodeFramework,
  componentCode: string
): Record<string, string> | null {
  switch (framework) {
    case 'Vue':
      return vueFiles(componentCode)
    case 'React':
      return reactFiles(componentCode)
    default:
      return null
  }
}

export function buildProjectZip(framework: CodeFramework, componentCode: string): Uint8Array | null {
  const files = buildProjectFiles(framework, componentCode)
  if (!files) return null
  const entries: Record<string, Uint8Array> = {}
  for (const [path, content] of Object.entries(files)) {
    entries[path] = strToU8(content)
  }
  return zipSync(entries, { level: 6 })
}

/** 浏览器侧触发 zip 下载；不支持的框架返回 false */
export function downloadProjectZip(framework: CodeFramework, componentCode: string): boolean {
  const zipped = buildProjectZip(framework, componentCode)
  if (!zipped) return false
  const blob = new Blob([zipped.buffer as ArrayBuffer], { type: 'application/zip' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `lutris-${framework.toLowerCase()}-app.zip`
  a.click()
  URL.revokeObjectURL(url)
  return true
}
