<script setup lang="ts">
import Prism from 'prismjs'
import 'prismjs/components/prism-jsx'
import 'prismjs/components/prism-markup'
import 'prismjs/components/prism-css'
import { ScrollAreaRoot, ScrollAreaScrollbar, ScrollAreaThumb, ScrollAreaViewport } from 'reka-ui'
import { computed, ref, watch } from 'vue'

import { selectionToJSX, selectionToCode } from '@open-pencil/core'
import { useEditorStore } from '@/stores/editor'
import { useBrand } from '@/composables/use-brand'

import type { JSXFormat } from '@open-pencil/core'

const store = useEditorStore()
const { config: brandConfig, exportBrandCSS } = useBrand()
const copied = ref(false)
const jsxFormat = ref<JSXFormat>('tailwind')
const responsive = ref(false)

type OutputFormat = 'jsx' | 'vue-sfc' | 'react' | 'svelte' | 'html-css'
const outputFormat = ref<OutputFormat>('jsx')
const OUTPUT_FORMATS: { value: OutputFormat; label: string }[] = [
  { value: 'jsx', label: 'JSX' },
  { value: 'vue-sfc', label: 'Vue 3' },
  { value: 'react', label: 'React' },
  { value: 'svelte', label: 'Svelte' },
  { value: 'html-css', label: 'HTML+CSS' },
]

function cycleOutputFormat() {
  const idx = OUTPUT_FORMATS.findIndex(f => f.value === outputFormat.value)
  outputFormat.value = OUTPUT_FORMATS[(idx + 1) % OUTPUT_FORMATS.length].value
}

function toggleFormat() {
  jsxFormat.value = jsxFormat.value === 'openpencil' ? 'tailwind' : 'openpencil'
}

const rawJSX = computed(() => {
  void store.state.sceneVersion
  const ids = [...store.state.selectedIds]
  if (ids.length === 0) return ''
  return selectionToJSX(ids, store.graph, jsxFormat.value)
})

// ── Brand token CSS custom properties ──
const brandTokens = computed(() => {
  const b = brandConfig.value
  return `  --brand-primary: ${b.primaryColor};
  --brand-secondary: ${b.secondaryColor};
  --brand-accent: ${b.accentColor};
  --brand-font: '${b.fontFamily}', sans-serif;
  --brand-radius: ${b.borderRadius}px;`
})

// ── Responsive media queries ──
function addResponsiveWrapper(code: string): string {
  if (!responsive.value) return code
  return `/* Responsive breakpoints */
@media (max-width: 768px) {
  /* Mobile styles */
}
@media (min-width: 769px) and (max-width: 1024px) {
  /* Tablet styles */
}
@media (min-width: 1025px) {
  /* Desktop styles */
}

${code}`
}

// ── Component name extraction ──
const componentName = computed(() => {
  const ids = [...store.state.selectedIds]
  if (ids.length !== 1) return 'Component'
  const node = store.graph.nodes.get(ids[0])
  if (!node?.name) return 'Component'
  return node.name.replace(/[^a-zA-Z0-9]/g, '').replace(/^[a-z]/, c => c.toUpperCase()) || 'Component'
})

function wrapVueSFC(jsx: string): string {
  const indent = jsx.split('\n').map(l => '    ' + l).join('\n')
  const scriptOpen = '<' + 'script setup lang="ts">'
  const scriptClose = '</' + 'script>'
  const styleOpen = '<' + 'style scoped>'
  const styleClose = '</' + 'style>'
  return `${scriptOpen}
// Generated by Lutris.ai — ${componentName.value}
${scriptClose}

<template>
${indent}
</template>

${styleOpen}
:root {
${brandTokens.value}
}
${responsive.value ? addResponsiveWrapper('') : ''}
${styleClose}`
}

function wrapReactComponent(jsx: string): string {
  const indent = jsx.split('\n').map(l => '      ' + l).join('\n')
  const name = componentName.value
  return `import React from 'react'

interface ${name}Props {
  className?: string
}

export default function ${name}({ className }: ${name}Props) {
  return (
    <div className={className}>
${indent}
    </div>
  )
}`
}

function wrapSvelteComponent(jsx: string): string {
  const indent = jsx.split('\n').map(l => '  ' + l).join('\n')
  const sOpen = '<' + 'script lang="ts">'
  const sClose = '</' + 'script>'
  const stOpen = '<' + 'style>'
  const stClose = '</' + 'style>'
  return `${sOpen}
  // Generated by Lutris.ai — ${componentName.value}
${sClose}

${indent}

${stOpen}
:root {
${brandTokens.value}
}
${stClose}`
}

function wrapHTMLCSS(jsx: string): string {
  const stOpen = '<' + 'style>'
  const stClose = '</' + 'style>'
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${componentName.value}</title>
  ${stOpen}
    :root {
${brandTokens.value}
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: var(--brand-font); }
${responsive.value ? addResponsiveWrapper('') : ''}
  ${stClose}
</head>
<body>
${jsx}
</body>
</html>`
}

const jsxCode = computed(() => {
  void store.state.sceneVersion
  const ids = [...store.state.selectedIds]
  if (ids.length === 0) return ''

  switch (outputFormat.value) {
    case 'vue-sfc': return selectionToCode(ids, store.graph, 'vue-sfc')
    case 'react': return selectionToCode(ids, store.graph, 'react')
    case 'html-css': return selectionToCode(ids, store.graph, 'html')
    case 'svelte': return wrapSvelteComponent(rawJSX.value)
    default: return rawJSX.value
  }
})

const highlightedLines = computed(() => {
  if (!jsxCode.value) return []
  const grammar = Prism.languages.jsx ?? Prism.languages.javascript
  return jsxCode.value.split('\n').map((line) => Prism.highlight(line, grammar, 'jsx'))
})

let copyTimeout: number | undefined

function copyCode() {
  navigator.clipboard.writeText(jsxCode.value)
  copied.value = true
  clearTimeout(copyTimeout)
  copyTimeout = setTimeout(() => (copied.value = false), 2000)
}

watch(jsxCode, () => {
  copied.value = false
})
</script>

<template>
  <div
    v-if="!jsxCode"
    data-test-id="code-panel-empty"
    class="flex flex-1 items-center justify-center px-4 text-center"
  >
    <span class="text-xs text-muted">Select a layer to see its code</span>
  </div>

  <div v-else data-test-id="code-panel" class="flex min-h-0 flex-1 flex-col">
    <div
      data-test-id="code-panel-header"
      class="flex shrink-0 items-center justify-between border-b border-border px-3 py-1.5"
    >
      <div class="flex items-center gap-1">
        <button
          data-test-id="code-panel-output-toggle"
          class="rounded bg-hover px-1.5 py-0.5 text-[11px] font-semibold text-surface"
          @click="cycleOutputFormat"
        >
          {{ OUTPUT_FORMATS.find(f => f.value === outputFormat)?.label }}
        </button>
        <button
          data-test-id="code-panel-format-toggle"
          class="rounded px-1.5 py-0.5 text-[11px] text-muted hover:bg-hover hover:text-surface"
          @click="toggleFormat"
        >
          {{ jsxFormat === 'openpencil' ? 'JSX' : 'Tailwind' }}
        </button>
        <button
          class="rounded px-1.5 py-0.5 text-[11px]"
          :class="responsive ? 'bg-accent/20 text-accent' : 'text-muted hover:bg-hover hover:text-surface'"
          @click="responsive = !responsive"
        >
          RWD
        </button>
      </div>
      <button
        data-test-id="code-panel-copy"
        class="flex items-center gap-1 rounded px-1.5 py-0.5 text-[11px] text-muted hover:bg-hover hover:text-surface"
        @click="copyCode"
      >
        <icon-lucide-check v-if="copied" class="size-3 text-green-400" />
        <icon-lucide-copy v-else class="size-3" />
        {{ copied ? 'Copied' : 'Copy' }}
      </button>
    </div>

    <!-- Component name -->
    <div class="shrink-0 border-b border-border px-3 py-1 text-[10px] text-muted">
      {{ componentName }}.{{ outputFormat === 'vue-sfc' ? 'vue' : outputFormat === 'svelte' ? 'svelte' : outputFormat === 'html-css' ? 'html' : 'tsx' }}
    </div>

    <ScrollAreaRoot class="min-h-0 flex-1">
      <ScrollAreaViewport class="size-full">
        <div class="p-3">
          <div v-for="(html, i) in highlightedLines" :key="i" class="flex text-xs leading-5">
            <span
              class="mr-3 shrink-0 text-right text-muted/40 select-none"
              style="min-width: 1.5em"
            >{{ i + 1 }}</span>
            <pre
              class="m-0 min-w-0 flex-1 break-words whitespace-pre-wrap"
            ><code v-html="html" /></pre>
          </div>
        </div>
      </ScrollAreaViewport>
      <ScrollAreaScrollbar orientation="vertical" class="flex w-1.5 touch-none p-px select-none">
        <ScrollAreaThumb class="relative flex-1 rounded-full bg-muted/20" />
      </ScrollAreaScrollbar>
    </ScrollAreaRoot>
  </div>
</template>

<style>
.token.tag { color: #7dd3fc; }
.token.attr-name { color: #c4b5fd; }
.token.attr-value, .token.string { color: #86efac; }
.token.number { color: #fca5a5; }
.token.punctuation { color: #888; }
.token.boolean { color: #fca5a5; }
.token.keyword { color: #c4b5fd; }
</style>
